# generated by datamodel-codegen:
#   filename:  http://0.0.0.0:8000/api/v1/openapi.json
#   timestamp: 2025-03-19T10:01:50+00:00

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from geojson_pydantic import Feature
from pydantic import BaseModel, EmailStr, Field, RootModel, constr


class BaseModelModel(BaseModel):
    pass


class FarmCreate(BaseModel):
    name: constr(max_length=255) = Field(..., title='Name')
    location: constr(max_length=255) | None = Field(None, title='Location')


class FarmPublic(BaseModel):
    name: constr(max_length=255) = Field(..., title='Name')
    location: constr(max_length=255) | None = Field(None, title='Location')
    id: UUID = Field(..., title='Id')
    owner_id: UUID = Field(..., title='Owner Id')


class FarmUpdate(BaseModel):
    name: constr(min_length=1, max_length=255) | None = Field(None, title='Name')
    location: constr(max_length=255) | None = Field(None, title='Location')


class FarmsPublic(BaseModel):
    data: list[FarmPublic] = Field(..., title='Data')
    count: int = Field(..., title='Count')


class FieldUpdate(BaseModel):
    name: constr(min_length=1, max_length=255) | None = Field(None, title='Name')
    area: float | str | None = Field(None, title='Area')
    soil_type: constr(max_length=100) | None = Field(None, title='Soil Type')


class ItemCreate(BaseModel):
    title: constr(min_length=1, max_length=255) = Field(..., title='Title')
    description: constr(max_length=255) | None = Field(None, title='Description')


class ItemPublic(BaseModel):
    title: constr(min_length=1, max_length=255) = Field(..., title='Title')
    description: constr(max_length=255) | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    owner_id: UUID = Field(..., title='Owner Id')


class ItemUpdate(BaseModel):
    title: constr(min_length=1, max_length=255) | None = Field(None, title='Title')
    description: constr(max_length=255) | None = Field(None, title='Description')


class ItemsPublic(BaseModel):
    data: list[ItemPublic] = Field(..., title='Data')
    count: int = Field(..., title='Count')


class Message(BaseModel):
    message: str = Field(..., title='Message')


class PrivateUserCreate(BaseModel):
    email: str = Field(..., title='Email')
    password: str = Field(..., title='Password')
    full_name: str = Field(..., title='Full Name')
    is_verified: bool = Field(False, title='Is Verified')


class UpdatePassword(BaseModel):
    current_password: constr(min_length=8, max_length=40) = Field(
        ..., title='Current Password'
    )
    new_password: constr(min_length=8, max_length=40) = Field(..., title='New Password')


class UserCreate(BaseModel):
    email: EmailStr = Field(..., title='Email')
    is_active: bool = Field(True, title='Is Active')
    is_superuser: bool = Field(False, title='Is Superuser')
    full_name: constr(max_length=255) | None = Field(None, title='Full Name')
    password: constr(min_length=8, max_length=40) = Field(..., title='Password')


class UserPublic(BaseModel):
    email: EmailStr = Field(..., title='Email')
    is_active: bool = Field(True, title='Is Active')
    is_superuser: bool = Field(False, title='Is Superuser')
    full_name: constr(max_length=255) | None = Field(None, title='Full Name')
    id: UUID = Field(..., title='Id')


class UserRegister(BaseModel):
    email: EmailStr = Field(..., title='Email')
    password: constr(min_length=8, max_length=40) = Field(..., title='Password')
    full_name: constr(max_length=255) | None = Field(None, title='Full Name')


class UserUpdate(BaseModel):
    email: EmailStr | None = Field(None, title='Email')
    is_active: bool = Field(True, title='Is Active')
    is_superuser: bool = Field(False, title='Is Superuser')
    full_name: constr(max_length=255) | None = Field(None, title='Full Name')
    password: constr(min_length=8, max_length=40) | None = Field(None, title='Password')


class UserUpdateMe(BaseModel):
    full_name: constr(max_length=255) | None = Field(None, title='Full Name')
    email: EmailStr | None = Field(None, title='Email')


class UsersPublic(BaseModel):
    data: list[UserPublic] = Field(..., title='Data')
    count: int = Field(..., title='Count')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class FieldCreate(BaseModel):
    name: constr(max_length=255) = Field(..., title='Name')
    area: float | str | None = Field(None, title='Area')
    soil_type: constr(max_length=100) | None = Field(None, title='Soil Type')
    feature: Feature | None = None


class FieldPublic(BaseModel):
    name: constr(max_length=255) = Field(..., title='Name')
    area: float | str | None = Field(None, title='Area')
    soil_type: constr(max_length=100) | None = Field(None, title='Soil Type')
    id: UUID = Field(..., title='Id')
    farm_id: UUID = Field(..., title='Farm Id')
    feature: Feature | None = None


class FieldsPublic(BaseModel):
    data: list[FieldPublic] = Field(..., title='Data')
    count: int = Field(..., title='Count')



def to_dict(self):
    return self.model_dump()

BaseModel.to_dict = to_dict

