services:

  db:
    # postgis/postgis isn't build for arm processors
    image: ghcr.io/baosystems/postgis:17
    restart: "no"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    command:
      [
        "postgres",
        "-c", "log_statement=all",
        "-c", "log_min_error_statement=ERROR",
        "-c", "log_min_messages=INFO",
      ]
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD?Variable not set}
      - POSTGRES_USER=${DATABASE_USER?Variable not set}
      - POSTGRES_DB=${DATABASE_DB?Variable not set}


  farmbase:
    ports:
      - "8000:8000"
    build:
      dockerfile: apps/farmbase/Dockerfile
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - /Users/markns/.config/gcloud:/gcloud
    env_file:
      - .env

    environment:
      DATABASE_HOSTNAME: db
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud/application_default_credentials.json

    deploy:
      resources:
        limits:
#          cpus: '1'
          memory: 2048M

volumes:
  app-db-data:
