### Get farms
GET http://127.0.0.1:8000/api/v1/default/farms
### Create farm
POST http://127.0.0.1:8000/api/v1/default/farms
Content-Type: application/json

{
  "farm_name": "Bobs's farm"
}
### Create farm with location
POST http://127.0.0.1:8000/api/v1/default/farms
Content-Type: application/json

{
  "farm_name": "Maggie's farm",
  "location": {
    "latitude": 0.1,
    "longitude": 0.1
  }
}

### Create farm with contacts
POST http://127.0.0.1:8000/api/v1/default/farms
Content-Type: application/json

{
  "farm_name": "Rafiki farm",
  "contacts": [
    {
      "contact_id": 1,
      "role": "owner"
    }
  ],
  "location": {
    "latitude": -0.365739,
    "longitude": 35.809071
  }

}

