###
POST http://127.0.0.1:8000/api/v1/default/contacts
Content-Type: application/json

{
  "name": "Mark",
  "phone_number": "31657775781",
  "preferred_form_of_address": "Mark",
  "gender": "male",
  "date_of_birth": null,
  "estimated_age": 40,
  "role": "farmer",
  "experience": 2,
  "email": null
}
###
# This is get or create
PUT http://127.0.0.1:8000/api/v1/default/contacts
Content-Type: application/json

{
  "name": "Mark",
  "phone_number": "+31657775784",
  "location": {
    "longitude": 0.1,
    "latitude": 0.1
  }
}

###
PATCH http://127.0.0.1:8000/api/v1/default/contacts/2
Content-Type: application/json

{
  "location": {
    "latitude": -0.1278,
    "longitude": 52.5074
  }
}
###
GET http://127.0.0.1:8000/api/v1/default/contacts/1
Content-Type: application/json
###
GET http://127.0.0.1:8000/api/v1/default/contacts/by-phone?phone=31657775781
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/v1/default/contacts
Content-Type: application/json

###
DELETE http://127.0.0.1:8000/api/v1/default/contacts/1
Content-Type: application/json

