[project]
name = "farmwise"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "<=3.13"
dependencies = [
    "farmbase-agent-toolkit",
    "farmwise-schema",
    "openai>=1.77.0",
    "openai-agents>=0.0.14",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
#    "basedpyright>0",
    "poethepoet>0",
    "pytest>0",
    "ruff>0",
]

[tool.uv.sources]
farmbase-agent-toolkit = { workspace = true }
farmwise-schema = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
