services:
  temporal:
    container_name: temporal
    image: temporalio/server:${TEMPORAL_VERSION:-1.28}
    env_file: .env
    restart: always
    networks:
      - temporal-network
    ports:
      - 7233:7233 # Expose gRPC frontend port
    volumes:
      - ./certs:/etc/temporal/certs
      - ./base.yaml:/etc/temporal/config/base.yaml

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:${TEMPORAL_UI_VERSION-2.38.3}
    env_file: .env.ui
    restart: always
    depends_on:
      - temporal
    networks:
      - temporal-network
    ports:
      - 8080:8080 # Expose Web UI port
    volumes:
      - ./ui.yaml:/etc/temporal/config/development.yaml
      - ./certs:/etc/temporal/certs
#  temporal-admin-tools:
#    container_name: temporal-admin-tools
#    depends_on:
#      - temporal
#    environment:
#      - TEMPORAL_ADDRESS=temporal:7233
#      - TEMPORAL_CLI_ADDRESS=temporal:7233
#    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
#    networks:
#      - temporal-network
#    stdin_open: true
#    tty: true
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
