[project]
name = "farmbase"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    #    "postmodern-greeter",
    "fastapi[standard]>=0.115.8",
]

[dependency-groups]
dev = [
#    "basedpyright>0",
    "poethepoet>0",
    "pytest>0",
    "ruff>0",
]

[tool.uv.sources]

# TODO: use https://github.com/fastapi/full-stack-fastapi-template


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
