[project]
name = "farmbase"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.15.1",
    "email-validator>=2.2.0",
    "emails>=0.6",
    "fastapi[standard]>=0.115.8",
    "geoalchemy2>=0.17.1",
    "geojson-pydantic>=1.2.0",
    "passlib[bcrypt]>=1.7.4",
    "psycopg[binary]>=3.2.5",
    "pydantic-settings>=2.6.1",
    "pyjwt>=2.10.1",
    "sentry-sdk>=2.23.1",
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
#    "basedpyright>0",
    "poethepoet>0",
    "pytest>0",
    "ruff>0",
]

[tool.uv.sources]

# TODO: use https://github.com/fastapi/full-stack-fastapi-template


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
